version: '3'

services:
  chat_app:
    image: shankentsang/chat_appv2
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: chat_db
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: mysecretpassword

volumes:
  mariadb_data:
